{
 "title": "Leipzig giesst",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Gesamtauswertung (Allzeit)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aktuelle Benutzeranzahl",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(created)\nFROM users"
      }
     ]
    },
    {
     "title": "Baumadoptionen",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__unixEpochGroupAlias(0,$__interval),\n  count(id) AS \"id\"\nFROM trees_adopted\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Aktuelle Anzahl Bäume",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(distinct(id))\nFROM trees"
      }
     ]
    },
    {
     "title": "Adoptierte Bäume",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__unixEpochGroupAlias(0,$__interval),\n  count(distinct(tree_id)) AS \"id\"\nFROM trees_adopted\nGROUP BY 1\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Gesamtauswertung (für gewählten Zeitraum)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gegossene Liter",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  sum(CAST (amount AS INTEGER)) AS \"Liter (Summe)\"\nFROM trees_watered\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Benutzerregistrierungen",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(created,$__interval,NULL),\n  count(uuid)\nFROM users\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Neue Benutzer",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(created)\nFROM users\nwhere $__timeFilter(created)"
      }
     ]
    },
    {
     "title": "Benutzeranzahl",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(*)\nFROM users\nwhere created <= $__timeTo()"
      }
     ]
    },
    {
     "title": "Anzahl Wässerungen",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__unixEpochGroupAlias(0,$__interval),\n  count(timestamp) AS \"id\"\nFROM trees_watered\nwhere $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Anzahl Gießer",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__unixEpochGroupAlias(0,$__interval),\n  count(distinct(uuid)) AS \"id\"\nFROM trees_watered\nwhere $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Anzahl bewässerte Bäume",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__unixEpochGroupAlias(0,$__interval),\n  count(distinct(tree_id)) AS \"id\"\nFROM trees_watered\nwhere $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Gegossene Liter",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__unixEpochGroupAlias(0,$__interval),\n  sum(CAST (amount AS INTEGER)) AS \"liter\"\nFROM trees_watered\nwhere $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Gießer-Rangliste nach gegossenen Litern",
     "type": "table",
     "gridPos": { "h": 11, "w": 9, "x": 0, "y": 16 },
     "targets": [
      {
       "rawSql": "select row_number() over(order by sum(CAST (tw.amount AS INTEGER)) desc) Rang, tw.username AS Benutzer, sum(CAST (tw.amount AS INTEGER)) as gegossen from trees_watered tw where $__timeFilter(tw.timestamp) group by tw.uuid, tw.username order by gegossen desc"
      }
     ]
    },
    {
     "title": "Nutzer, die mehr als einen Baum gegossen haben",
     "type": "table",
     "gridPos": { "h": 11, "w": 8, "x": 9, "y": 16 },
     "targets": [
      {
       "rawSql": "select row_number() over(order by count(distinct(tree_id)) desc) AS Rang, username AS Benutzer, count(distinct(tree_id)) as baum_anzahl from trees_watered where $__timeFilter(timestamp) group by username having count(distinct(tree_id)) > 1 order by baum_anzahl desc"
      }
     ]
    },
    {
     "title": "Nutzer, die mehr als einmal gegossen haben",
     "type": "table",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 16 },
     "targets": [
      {
       "rawSql": "select row_number() over(order by count(*) desc) AS rang, username AS Benutzer, count(*) as giess_anzahl from trees_watered where $__timeFilter(timestamp) group by username having count(*) > 1 order by giess_anzahl desc"
      }
     ]
    }
   ]
  },
  {
   "title": "Gesamtauswertung (2022)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Neue Benutzer",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(created)\nFROM users\nwhere created >= '2022-01-01 00:00:00.000'"
      }
     ]
    },
    {
     "title": "Benutzeranzahl",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "rawSql": "SELECT\n  count(*)\nFROM users" }
     ]
    },
    {
     "title": "Anzahl Wässerungen",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__unixEpochGroupAlias(0,$__interval),\n  count(timestamp) AS \"id\"\nFROM trees_watered\nwhere timestamp >= '2022-01-01 00:00:00.000'\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Anzahl Gießer",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__unixEpochGroupAlias(0,$__interval),\n  count(distinct(uuid)) AS \"id\"\nFROM trees_watered\nwhere timestamp >= '2022-01-01 00:00:00.000'\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Anzahl bewässerte Bäume",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__unixEpochGroupAlias(0,$__interval),\n  count(distinct(tree_id)) AS \"id\"\nFROM trees_watered\nwhere timestamp >= '2022-01-01 00:00:00.000'\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Gegossene Liter",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__unixEpochGroupAlias(0,$__interval),\n  sum(CAST (amount AS INTEGER)) AS \"liter\"\nFROM trees_watered\nwhere timestamp >= '2022-01-01 00:00:00.000'\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Gießer-Rangliste nach gegossenen Litern",
     "type": "table",
     "gridPos": { "h": 11, "w": 9, "x": 0, "y": 8 },
     "targets": [
      {
       "rawSql": "select row_number() over(order by sum(CAST (tw.amount AS INTEGER)) desc) Rang, tw.username AS Benutzer, sum(CAST (tw.amount AS INTEGER)) as gegossen from trees_watered tw where tw.timestamp >= '2022-01-01 00:00:00.000' group by tw.uuid, tw.username order by gegossen desc"
      }
     ]
    },
    {
     "title": "Nutzer, die mehr als einen Baum gegossen haben",
     "type": "table",
     "gridPos": { "h": 11, "w": 8, "x": 9, "y": 8 },
     "targets": [
      {
       "rawSql": "select row_number() over(order by count(distinct(tree_id)) desc) AS Rang, username AS Benutzer, count(distinct(tree_id)) as baum_anzahl from trees_watered where timestamp >= '2022-01-01 00:00:00.000' group by username having count(distinct(tree_id)) > 1 order by baum_anzahl desc"
      }
     ]
    },
    {
     "title": "Nutzer, die mehr als einmal gegossen haben",
     "type": "table",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 8 },
     "targets": [
      {
       "rawSql": "select row_number() over(order by count(*) desc) AS rang, username AS Benutzer, count(*) as giess_anzahl from trees_watered where timestamp >= '2022-01-01 00:00:00.000' group by username having count(*) > 1 order by giess_anzahl desc"
      }
     ]
    }
   ]
  },
  {
   "title": "Auswertung nach Stadtteilen (für gewählten Zeitraum)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gegossene Liter nach Ortsteilen",
     "type": "table",
     "gridPos": { "h": 11, "w": 7, "x": 0, "y": 4 },
     "targets": [
      {
       "rawSql": "select row_number() over(order by sum(CAST (tw.amount AS INTEGER)) desc) Rang, t.bezirk AS Ortsteil, sum(CAST (tw.amount AS INTEGER)) as gegossen from trees_watered tw join trees t on tw.tree_id = t.id where $__timeFilter(tw.timestamp) group by tw.uuid, t.bezirk order by gegossen desc\r\n"
      }
     ]
    },
    {
     "title": "Bäume nach Ortsteile, die mehr als einmal gegossen worden sind",
     "type": "table",
     "gridPos": { "h": 11, "w": 10, "x": 7, "y": 4 },
     "targets": [
      {
       "rawSql": "select row_number() over(order by count(distinct(tw.tree_id)) desc) AS Rang, bezirk AS Ortsteil, count(distinct(tw.tree_id)) as baum_anzahl from trees_watered tw join trees t on tw.tree_id = t.id where $__timeFilter(tw.timestamp) group by t.bezirk having count(distinct(tw.tree_id)) > 1 order by baum_anzahl desc"
      }
     ]
    },
    {
     "title": "Gießungen nach Ortsteilen",
     "type": "table",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 4 },
     "targets": [
      {
       "rawSql": "select row_number() over(order by count(*) desc) AS rang, t.bezirk as Ortsteil, count(*) as giess_anzahl from trees_watered tw join trees t on tw.tree_id = t.id where $__timeFilter(tw.timestamp) group by t.bezirk having count(*) > 1 order by giess_anzahl desc, t.bezirk"
      }
     ]
    },
    {
     "title": "Anzahl Gießende nach Ortsteil",
     "type": "table",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 15 },
     "targets": [
      {
       "rawSql": "select row_number() over(order by count(distinct(username)) desc) AS rang, t.bezirk as Ortsteil, count(distinct(username)) as nutzer_anzahl from trees_watered tw join trees t on tw.tree_id = t.id where $__timeFilter(tw.timestamp) group by t.bezirk order by nutzer_anzahl desc, t.bezirk\r\n"
      }
     ]
    },
    {
     "title": "Gießer mit Ortsteil nach Anzahl Gießungen",
     "type": "table",
     "gridPos": { "h": 11, "w": 16, "x": 8, "y": 15 },
     "targets": [
      {
       "rawSql": "select row_number() over(order by count(*) desc) AS rang, t.bezirk as Ortsteil, tw.username, count(*) as giess_anzahl from trees_watered tw join trees t on tw.tree_id = t.id where $__timeFilter(tw.timestamp) group by t.bezirk, tw.username having count(*) > 1 order by giess_anzahl desc, t.bezirk\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Auswertung nach Stadtteilen (2022)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gegossene Liter nach Ortsteilen",
     "type": "table",
     "gridPos": { "h": 11, "w": 7, "x": 0, "y": 5 },
     "targets": [
      {
       "rawSql": "select row_number() over(order by sum(CAST (tw.amount AS INTEGER)) desc) Rang, t.bezirk AS Ortsteil, sum(CAST (tw.amount AS INTEGER)) as gegossen from trees_watered tw join trees t on tw.tree_id = t.id  where tw.timestamp >= '2022-01-01 00:00:00.000' group by tw.uuid, t.bezirk order by gegossen desc\r\n"
      }
     ]
    },
    {
     "title": "Bäume nach Ortsteile, die mehr als einmal gegossen worden sind",
     "type": "table",
     "gridPos": { "h": 11, "w": 10, "x": 7, "y": 5 },
     "targets": [
      {
       "rawSql": "select row_number() over(order by count(distinct(tw.tree_id)) desc) AS Rang, bezirk AS Ortsteil, count(distinct(tw.tree_id)) as baum_anzahl from trees_watered tw join trees t on tw.tree_id = t.id where tw.timestamp >= '2022-01-01 00:00:00.000' group by t.bezirk having count(distinct(tw.tree_id)) > 1 order by baum_anzahl desc"
      }
     ]
    },
    {
     "title": "Gießungen nach Ortsteilen",
     "type": "table",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 5 },
     "targets": [
      {
       "rawSql": "select row_number() over(order by count(*) desc) AS rang, t.bezirk as Ortsteil, count(*) as giess_anzahl from trees_watered tw join trees t on tw.tree_id = t.id where tw.timestamp >= '2022-01-01 00:00:00.000' group by t.bezirk having count(*) > 1 order by giess_anzahl desc, t.bezirk"
      }
     ]
    },
    {
     "title": "Anzahl Gießende nach Ortsteil",
     "type": "table",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 16 },
     "targets": [
      {
       "rawSql": "select row_number() over(order by count(distinct(username)) desc) AS rang, t.bezirk as Ortsteil, count(distinct(username)) as nutzer_anzahl from trees_watered tw join trees t on tw.tree_id = t.id where tw.timestamp >= '2022-01-01 00:00:00.000' group by t.bezirk order by nutzer_anzahl desc, t.bezirk\r\n"
      }
     ]
    },
    {
     "title": "Gießer mit Ortsteil nach Anzahl Gießungen",
     "type": "table",
     "gridPos": { "h": 11, "w": 16, "x": 8, "y": 16 },
     "targets": [
      {
       "rawSql": "select row_number() over(order by count(*) desc) AS rang, t.bezirk as Ortsteil, tw.username, count(*) as giess_anzahl from trees_watered tw join trees t on tw.tree_id = t.id where tw.timestamp >= '2022-01-01 00:00:00.000' group by t.bezirk, tw.username having count(*) > 1 order by giess_anzahl desc, t.bezirk\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Tageszeitauswertung (für gewählten Zeitraum)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wässerungen nach Tageszeit",
     "type": "marcusolsson-hourly-heatmap-panel",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  amount::numeric::integer AS value\nFROM trees_watered\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "Gießpatentschaften",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gießpatenschaften",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "rawSql": "SELECT\n  t.id, t.standortnr, u.email, t.strname, t.pflanzjahr, t.gattung, t.artdtsch\nFROM users u JOIN trees_adopted a ON a.uuid = u.uuid JOIN trees t ON t.id = a.tree_id\nORDER BY u.email"
      }
     ]
    }
   ]
  },
  {
   "title": "Karte (für gewählten Zeitraum)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gießkarte",
     "type": "grafana-worldmap-panel",
     "gridPos": { "h": 14, "w": 23, "x": 0, "y": 7 },
     "valueName": "max",
     "targets": [
      {
       "rawSql": "SELECT\n  t.id as tree,\n  tw.amount::numeric::integer as value,\n  t.lat::numeric::float as latitude,\n  t.lng::numeric::float as longitude\nFROM trees_watered tw JOIN trees t ON tw.tree_id = t.id\nWHERE\n  $__timeFilter(timestamp)"
      }
     ]
    }
   ]
  },
  {
   "title": "Baumalter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Anzahl Bäume im Alter von 10 bis 15 Jahren",
     "type": "table",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "select count(*) from trees where pflanzjahr IS NOT NULL AND pflanzjahr::int >= 2006 and pflanzjahr::int <= 2010 "
      }
     ]
    }
   ]
  }
 ]
}