{
 "title": "LeipzigGiesstPublic",
 "time": { "from": "2021-09-23T23:50:13.514Z", "to": "2023-09-23T23:50:13.514Z" },
 "templating": {
  "list": [
   { "name": "standort_nummer", "label": "Standortnummer", "query": "osm_6058038310" },
   { "name": "required_liters", "label": "Mindestliter", "query": "80" },
   { "name": "m2", "label": "m² Baumscheibengröße", "query": "4" }
  ]
 },
 "panels": [
  {
   "title": "Gesamtauswertung (Allzeit)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aktuelle Benutzeranzahl",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(created)\nFROM users"
      }
     ]
    },
    {
     "title": "Baumadoptionen",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__unixEpochGroupAlias(0,$__interval),\n  count(id) AS \"id\"\nFROM trees_adopted\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Aktuelle Anzahl Bäume",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(distinct(id))\nFROM trees"
      }
     ]
    },
    {
     "title": "Adoptierte Bäume",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__unixEpochGroupAlias(0,$__interval),\n  count(distinct(tree_id)) AS \"id\"\nFROM trees_adopted\nGROUP BY 1\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Gesamtauswertung (für gewählten Zeitraum)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gegossene Liter",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  sum(CAST (amount AS INTEGER)) AS \"Liter (Summe)\"\nFROM trees_watered\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Benutzerregistrierungen",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(created,$__interval,NULL),\n  count(uuid)\nFROM users\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Neue Benutzer",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(created)\nFROM users\nwhere $__timeFilter(created)"
      }
     ]
    },
    {
     "title": "Benutzeranzahl",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(*)\nFROM users\nwhere created <= $__timeTo()"
      }
     ]
    },
    {
     "title": "Anzahl Wässerungen",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__unixEpochGroupAlias(0,$__interval),\n  count(timestamp) AS \"id\"\nFROM trees_watered\nwhere $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Anzahl Gießer",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__unixEpochGroupAlias(0,$__interval),\n  count(distinct(uuid)) AS \"id\"\nFROM trees_watered\nwhere $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Anzahl bewässerte Bäume",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__unixEpochGroupAlias(0,$__interval),\n  count(distinct(tree_id)) AS \"id\"\nFROM trees_watered\nwhere $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Gegossene Liter",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__unixEpochGroupAlias(0,$__interval),\n  sum(CAST (amount AS INTEGER)) AS \"liter\"\nFROM trees_watered\nwhere $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Gesamtauswertung (2022)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Neue Benutzer",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(created)\nFROM users\nwhere created >= '2022-01-01 00:00:00.000'"
      }
     ]
    },
    {
     "title": "Benutzeranzahl",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "rawSql": "SELECT\n  count(*)\nFROM users" }
     ]
    },
    {
     "title": "Anzahl Wässerungen",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__unixEpochGroupAlias(0,$__interval),\n  count(timestamp) AS \"id\"\nFROM trees_watered\nwhere timestamp >= '2022-01-01 00:00:00.000'\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Anzahl Gießer",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__unixEpochGroupAlias(0,$__interval),\n  count(distinct(uuid)) AS \"id\"\nFROM trees_watered\nwhere timestamp >= '2022-01-01 00:00:00.000'\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Anzahl bewässerte Bäume",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__unixEpochGroupAlias(0,$__interval),\n  count(distinct(tree_id)) AS \"id\"\nFROM trees_watered\nwhere timestamp >= '2022-01-01 00:00:00.000'\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Gegossene Liter",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__unixEpochGroupAlias(0,$__interval),\n  sum(CAST (amount AS INTEGER)) AS \"liter\"\nFROM trees_watered\nwhere timestamp >= '2022-01-01 00:00:00.000'\nGROUP BY 1\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Auswertung nach Stadtteilen (für gewählten Zeitraum)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gegossene Liter nach Ortsteilen",
     "type": "table",
     "gridPos": { "h": 11, "w": 7, "x": 0, "y": 4 },
     "targets": [
      {
       "rawSql": "select row_number() over(order by sum(CAST (tw.amount AS INTEGER)) desc) Rang, t.bezirk AS Ortsteil, sum(CAST (tw.amount AS INTEGER)) as gegossen from trees_watered tw join trees t on tw.tree_id = t.id where $__timeFilter(tw.timestamp) group by tw.uuid, t.bezirk order by gegossen desc\r\n"
      }
     ]
    },
    {
     "title": "Bäume nach Ortsteile, die mehr als einmal gegossen worden sind",
     "type": "table",
     "gridPos": { "h": 11, "w": 10, "x": 7, "y": 4 },
     "targets": [
      {
       "rawSql": "select row_number() over(order by count(distinct(tw.tree_id)) desc) AS Rang, bezirk AS Ortsteil, count(distinct(tw.tree_id)) as baum_anzahl from trees_watered tw join trees t on tw.tree_id = t.id where $__timeFilter(tw.timestamp) group by t.bezirk having count(distinct(tw.tree_id)) > 1 order by baum_anzahl desc"
      }
     ]
    },
    {
     "title": "Gießungen nach Ortsteilen",
     "type": "table",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 4 },
     "targets": [
      {
       "rawSql": "select row_number() over(order by count(*) desc) AS rang, t.bezirk as Ortsteil, count(*) as giess_anzahl from trees_watered tw join trees t on tw.tree_id = t.id where $__timeFilter(tw.timestamp) group by t.bezirk having count(*) > 1 order by giess_anzahl desc, t.bezirk"
      }
     ]
    }
   ]
  },
  {
   "title": "Auswertung nach Stadtteilen (2022)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gegossene Liter nach Ortsteilen",
     "type": "table",
     "gridPos": { "h": 11, "w": 7, "x": 0, "y": 5 },
     "targets": [
      {
       "rawSql": "select row_number() over(order by sum(CAST (tw.amount AS INTEGER)) desc) Rang, t.bezirk AS Ortsteil, sum(CAST (tw.amount AS INTEGER)) as gegossen from trees_watered tw join trees t on tw.tree_id = t.id  where tw.timestamp >= '2022-01-01 00:00:00.000' group by tw.uuid, t.bezirk order by gegossen desc\r\n"
      }
     ]
    },
    {
     "title": "Bäume nach Ortsteile, die mehr als einmal gegossen worden sind",
     "type": "table",
     "gridPos": { "h": 11, "w": 10, "x": 7, "y": 5 },
     "targets": [
      {
       "rawSql": "select row_number() over(order by count(distinct(tw.tree_id)) desc) AS Rang, bezirk AS Ortsteil, count(distinct(tw.tree_id)) as baum_anzahl from trees_watered tw join trees t on tw.tree_id = t.id where tw.timestamp >= '2022-01-01 00:00:00.000' group by t.bezirk having count(distinct(tw.tree_id)) > 1 order by baum_anzahl desc"
      }
     ]
    },
    {
     "title": "Gießungen nach Ortsteilen",
     "type": "table",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 5 },
     "targets": [
      {
       "rawSql": "select row_number() over(order by count(*) desc) AS rang, t.bezirk as Ortsteil, count(*) as giess_anzahl from trees_watered tw join trees t on tw.tree_id = t.id where tw.timestamp >= '2022-01-01 00:00:00.000' group by t.bezirk having count(*) > 1 order by giess_anzahl desc, t.bezirk"
      }
     ]
    }
   ]
  },
  {
   "title": "Karte (für gewählten Zeitraum)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gießkarte",
     "type": "grafana-worldmap-panel",
     "gridPos": { "h": 14, "w": 23, "x": 0, "y": 6 },
     "valueName": "max",
     "targets": [
      {
       "rawSql": "SELECT\n  t.id as tree,\n  tw.amount::numeric::integer as value,\n  t.lat::numeric::float as latitude,\n  t.lng::numeric::float as longitude\nFROM trees_watered tw JOIN trees t ON tw.tree_id = t.id\nWHERE\n  $__timeFilter(timestamp)"
      }
     ]
    }
   ]
  },
  {
   "title": "Wöchentlich",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wöchentliche Gießungen",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT \n  date_part('year', timestamp::date) as year,\n  date_trunc('week', timestamp::date) AS weekly, \n  tree_id,\n  SUM(amount::int)\nFROM\n  trees_watered\nWHERE\n  timestamp >= '2022-01-01T00:00:00.000Z'\nGROUP BY year, weekly, tree_id\nORDER BY year, weekly, tree_id\n"
      }
     ]
    },
    {
     "title": "Gegossene aber inzwischen entfernte Bäume",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT tw.tree_id\nFROM\n  trees_watered tw\nLEFT OUTER JOIN \n  trees t\nON t.id = tw.tree_id\nWHERE\n  t.id IS null\nORDER by tw.tree_id   \n"
      }
     ]
    }
   ]
  },
  {
   "title": "Baumweise",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Summe Gegossene Liter je Baum nach Zeitraum",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "rawSql": "SELECT\n  tree_id,\n  sum(amount::INTEGER) AS \"litersumme\"\nFROM trees_watered\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY tree_id\nORDER BY litersumme"
      }
     ]
    }
   ]
  },
  {
   "title": "Niederschlag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Niederschlag Leipzig/Holzhausen täglich liter/m²",
     "type": "timeseries",
     "description": "mm = liter pro m²",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT\n  date AS \"time\",\n  mm\nFROM station_values\nWHERE\n  station_id = 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Niederschlag Leipzig/Holzhausen wöchentliche Summe liter/m²",
     "type": "timeseries",
     "description": "mm = liter pro m²",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT\n  date_trunc('week', date) AS weekly,\n  SUM(mm) as mm\nFROM station_values\nWHERE\n  station_id = 1\nGROUP BY weekly  \nORDER BY weekly"
      }
     ]
    },
    {
     "title": "Niederschlag Leipzig/Holzhausen wöchentliche Summe liter/$m2 m² (Baumscheibe)",
     "type": "timeseries",
     "description": "mm = liter pro m²",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT\n  date_trunc('week', date) AS weekly,\n  SUM(mm*$m2) as mm\nFROM station_values\nWHERE\n  station_id = 1\nGROUP BY weekly  \nORDER BY weekly"
      }
     ]
    },
    {
     "title": "wöchentlicher  Niederschlag (pro $m2 m²)  + gegossene Liter für den Baum mit der Standortnummer $standort_nummer",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT\n  v.mm as niederschlag,\n  g.gegossen as gegossen,\n  v.weekly_rain as time\nFROM (\nSELECT\n  date_trunc('week', s.date) AS weekly_rain,\n  SUM(s.mm*$m2) as mm\nFROM station_values AS s\nWHERE\n  s.station_id = 1\nGROUP BY weekly_rain  \n) AS v\n LEFT OUTER JOIN (\nSELECT\n  date_trunc('week', w.timestamp) AS weekly_watered,\n  SUM(CAST (w.amount AS integer)) as gegossen\nFROM trees_watered AS w JOIN trees t ON t.id = w.tree_id\nWHERE t.standortnr = '$standort_nummer'\nGROUP BY weekly_watered\n) AS g ON (g.weekly_watered = v.weekly_rain)\nWHERE $__timeFilter(v.weekly_rain)"
      }
     ]
    },
    {
     "title": "Bäume mit Anzahl Wochen, in denen >= $required_liters Liter (Regen ($m2 m²) + gegossen)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "rawSql": "SELECT t.id, t.standortnr as Standortnummer, count(*) AS AnzahlWochen \nFROM (\n  SELECT\n    g.tree_id as tree_id,\n    v.weekly_rain as weekly,\n    SUM(COALESCE(v.mm,0) + COALESCE(g.gegossen,0)) AS summe\n  FROM (\n    SELECT\n      date_trunc('week', s.date) AS weekly_rain,\n      SUM(s.mm*$m2) as mm\n    FROM station_values AS s\n    WHERE\n      s.station_id = 1\n    AND $__timeFilter(s.date)\n    GROUP BY weekly_rain  \n  ) AS v \n  LEFT OUTER JOIN (\n    SELECT\n      t.id as tree_id,\n      date_trunc('week', w.timestamp) AS weekly_watered,\n      SUM(CAST (w.amount AS integer)) as gegossen\n    FROM trees AS t LEFT OUTER JOIN trees_watered AS w ON t.id = w.tree_id\n    WHERE $__timeFilter(w.timestamp)\n    GROUP BY t.id, weekly_watered\n  ) AS g\n  ON (g.weekly_watered = v.weekly_rain)\n  GROUP BY g.tree_id, v.weekly_rain\n  HAVING SUM(COALESCE(v.mm,0) + COALESCE(g.gegossen,0)) >= $required_liters\n) AS a JOIN trees t ON t.id = a.tree_id\nGROUP BY t.id, t.standortnr\nORDER BY count(*) DESC"
      }
     ]
    },
    {
     "title": "Bäume mit Anzahl Wochen, in denen >= $required_liters Liter (nur Regen ($m2 m²))",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "rawSql": "SELECT t.id, t.standortnr as Standortnummer, count(*) AS AnzahlWochen \nFROM (\n  SELECT\n    g.tree_id as tree_id,\n    v.weekly_rain as weekly,\n    SUM(COALESCE(v.mm,0)) AS summe\n  FROM (\n    SELECT\n      date_trunc('week', s.date) AS weekly_rain,\n      SUM(s.mm*$m2) as mm\n    FROM station_values AS s\n    WHERE\n      s.station_id = 1\n    AND $__timeFilter(s.date)\n    GROUP BY weekly_rain  \n  ) AS v \n  LEFT OUTER JOIN (\n    SELECT\n      t.id as tree_id,\n      date_trunc('week', w.timestamp) AS weekly_watered,\n      SUM(CAST (w.amount AS integer)) as gegossen\n    FROM trees AS t LEFT OUTER JOIN trees_watered AS w ON t.id = w.tree_id\n    WHERE $__timeFilter(w.timestamp)\n    GROUP BY t.id, weekly_watered\n  ) AS g\n  ON (g.weekly_watered = v.weekly_rain)\n  GROUP BY g.tree_id, v.weekly_rain\n  HAVING SUM(COALESCE(v.mm,0)) >= $required_liters\n) AS a JOIN trees t ON t.id = a.tree_id\nGROUP BY t.id, t.standortnr\nORDER BY count(*) DESC"
      }
     ]
    },
    {
     "title": "Bäume mit Anzahl Wochen, in denen nur mit Gießen >= $required_liters Liter",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "rawSql": "SELECT t.id, t.standortnr as Standortnummer, count(*) AS AnzahlWochen \nFROM (\n  SELECT\n    g.tree_id as tree_id,\n    v.weekly_rain as weekly,\n    SUM(COALESCE(v.mm,0) + COALESCE(g.gegossen,0)) AS summe\n  FROM (\n    SELECT\n      date_trunc('week', s.date) AS weekly_rain,\n      SUM(s.mm*$m2) as mm\n    FROM station_values AS s\n    WHERE\n      s.station_id = 1\n    AND $__timeFilter(s.date)\n    GROUP BY weekly_rain  \n  ) AS v \n  LEFT OUTER JOIN (\n    SELECT\n      t.id as tree_id,\n      date_trunc('week', w.timestamp) AS weekly_watered,\n      SUM(CAST (w.amount AS integer)) as gegossen\n    FROM trees AS t LEFT OUTER JOIN trees_watered AS w ON t.id = w.tree_id\n    WHERE $__timeFilter(w.timestamp)\n    GROUP BY t.id, weekly_watered\n  ) AS g\n  ON (g.weekly_watered = v.weekly_rain)\n  GROUP BY g.tree_id, v.weekly_rain\n  HAVING SUM(COALESCE(v.mm,0)) < $required_liters AND SUM(COALESCE(v.mm,0) + COALESCE(g.gegossen,0)) >= $required_liters\n) AS a JOIN trees t ON t.id = a.tree_id\nGROUP BY t.id, t.standortnr\nORDER BY count(*) DESC"
      }
     ]
    },
    {
     "title": "Wochen, in denen >= $required_liters Liter Regen ($m2 m²)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "rawSql": "SELECT x.weekly_rain, x.mm\nFROM (\nSELECT\n  date_trunc('week', s.date) AS weekly_rain,\n  SUM(s.mm*$m2) as mm\nFROM station_values AS s\nWHERE\n  s.station_id = 1\nGROUP BY weekly_rain\n) AS x\nWHERE x.mm >= $required_liters\nAND $__timeFilter(weekly_rain)\nORDER BY weekly_rain ASC\n"
      }
     ]
    }
   ]
  }
 ]
}